# Path: ambiente/.venv/lib/python3.10/site-packages/numpy/typing/tests/data/pass/warnings_and_errors.py
# Purpose (en): <write English purpose here>
# Propósito (pt-BR): <escreva em Português aqui>

# Path: ambiente/.venv/lib/python3.10/site-packages/numpy/typing/tests/data/pass/warnings_and_errors.py
# Purpose (en): <write English purpose here>
# Propósito (pt-BR): <escreva em Português aqui>

import numpy.exceptions as ex

ex.AxisError("test")
ex.AxisError(1, ndim=2)
ex.AxisError(1, ndim=2, msg_prefix="error")
ex.AxisError(1, ndim=2, msg_prefix=None)
